version: '3.8'

services:
  socket-io-server:
    build: 
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./Server:/server
    working_dir: /server
    environment:
      - VITE_GLOBAL_IP=${VITE_GLOBAL_IP}
    command: node server.js
    
  tic-tac-toe-app:
    build: 
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./Client:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - VITE_GLOBAL_IP=${VITE_GLOBAL_IP}
    command: npm run dev
